"""baseline

Revision ID: 70daa6ea31f5
Revises: 
Create Date: 2026-06-06 17:58:59.677278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70daa6ea31f5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('bik', sa.String(), nullable=False),
    sa.Column('inn', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inn'),
    sa.UniqueConstraint('name')
    )
    op.create_table('periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('period')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_superadmin', sa.Boolean(), nullable=False),
    sa.Column('user_read', sa.Boolean(), nullable=False),
    sa.Column('user_modify', sa.Boolean(), nullable=False),
    sa.Column('user_create', sa.Boolean(), nullable=False),
    sa.Column('user_delete', sa.Boolean(), nullable=False),
    sa.Column('role_read', sa.Boolean(), nullable=False),
    sa.Column('role_modify', sa.Boolean(), nullable=False),
    sa.Column('role_create', sa.Boolean(), nullable=False),
    sa.Column('role_delete', sa.Boolean(), nullable=False),
    sa.Column('spec_region_read', sa.Boolean(), nullable=False),
    sa.Column('spec_region_modify', sa.Boolean(), nullable=False),
    sa.Column('spec_region_create', sa.Boolean(), nullable=False),
    sa.Column('spec_region_delete', sa.Boolean(), nullable=False),
    sa.Column('region_read', sa.Boolean(), nullable=False),
    sa.Column('region_modify', sa.Boolean(), nullable=False),
    sa.Column('region_create', sa.Boolean(), nullable=False),
    sa.Column('region_delete', sa.Boolean(), nullable=False),
    sa.Column('spec_arial_read', sa.Boolean(), nullable=False),
    sa.Column('spec_arial_modify', sa.Boolean(), nullable=False),
    sa.Column('spec_arial_create', sa.Boolean(), nullable=False),
    sa.Column('spec_arial_delete', sa.Boolean(), nullable=False),
    sa.Column('arial_read', sa.Boolean(), nullable=False),
    sa.Column('arial_modify', sa.Boolean(), nullable=False),
    sa.Column('arial_create', sa.Boolean(), nullable=False),
    sa.Column('arial_delete', sa.Boolean(), nullable=False),
    sa.Column('spec_locality_read', sa.Boolean(), nullable=False),
    sa.Column('spec_locality_modify', sa.Boolean(), nullable=False),
    sa.Column('spec_locality_create', sa.Boolean(), nullable=False),
    sa.Column('spec_locality_delete', sa.Boolean(), nullable=False),
    sa.Column('locality_read', sa.Boolean(), nullable=False),
    sa.Column('locality_modify', sa.Boolean(), nullable=False),
    sa.Column('locality_create', sa.Boolean(), nullable=False),
    sa.Column('locality_delete', sa.Boolean(), nullable=False),
    sa.Column('spec_street_read', sa.Boolean(), nullable=False),
    sa.Column('spec_street_modify', sa.Boolean(), nullable=False),
    sa.Column('spec_street_create', sa.Boolean(), nullable=False),
    sa.Column('spec_street_delete', sa.Boolean(), nullable=False),
    sa.Column('street_read', sa.Boolean(), nullable=False),
    sa.Column('street_modify', sa.Boolean(), nullable=False),
    sa.Column('street_create', sa.Boolean(), nullable=False),
    sa.Column('street_delete', sa.Boolean(), nullable=False),
    sa.Column('spec_build_read', sa.Boolean(), nullable=False),
    sa.Column('spec_build_modify', sa.Boolean(), nullable=False),
    sa.Column('spec_build_create', sa.Boolean(), nullable=False),
    sa.Column('spec_build_delete', sa.Boolean(), nullable=False),
    sa.Column('spec_room_read', sa.Boolean(), nullable=False),
    sa.Column('spec_room_modify', sa.Boolean(), nullable=False),
    sa.Column('spec_room_create', sa.Boolean(), nullable=False),
    sa.Column('spec_room_delete', sa.Boolean(), nullable=False),
    sa.Column('bank_read', sa.Boolean(), nullable=False),
    sa.Column('bank_modify', sa.Boolean(), nullable=False),
    sa.Column('bank_create', sa.Boolean(), nullable=False),
    sa.Column('bank_delete', sa.Boolean(), nullable=False),
    sa.Column('organization_read', sa.Boolean(), nullable=False),
    sa.Column('organization_modify', sa.Boolean(), nullable=False),
    sa.Column('organization_create', sa.Boolean(), nullable=False),
    sa.Column('organization_delete', sa.Boolean(), nullable=False),
    sa.Column('spec_contract_read', sa.Boolean(), nullable=False),
    sa.Column('spec_contract_modify', sa.Boolean(), nullable=False),
    sa.Column('spec_contract_create', sa.Boolean(), nullable=False),
    sa.Column('spec_contract_delete', sa.Boolean(), nullable=False),
    sa.Column('contract_read', sa.Boolean(), nullable=False),
    sa.Column('contract_modify', sa.Boolean(), nullable=False),
    sa.Column('contract_create', sa.Boolean(), nullable=False),
    sa.Column('contract_delete', sa.Boolean(), nullable=False),
    sa.Column('sub_contract_read', sa.Boolean(), nullable=False),
    sa.Column('sub_contract_create', sa.Boolean(), nullable=False),
    sa.Column('sub_contract_modify', sa.Boolean(), nullable=False),
    sa.Column('sub_contract_delete', sa.Boolean(), nullable=False),
    sa.Column('period_read', sa.Boolean(), nullable=False),
    sa.Column('period_modify', sa.Boolean(), nullable=False),
    sa.Column('period_create', sa.Boolean(), nullable=False),
    sa.Column('period_delete', sa.Boolean(), nullable=False),
    sa.Column('spec_equipment_read', sa.Boolean(), nullable=False),
    sa.Column('spec_equipment_modify', sa.Boolean(), nullable=False),
    sa.Column('spec_equipment_create', sa.Boolean(), nullable=False),
    sa.Column('spec_equipment_delete', sa.Boolean(), nullable=False),
    sa.Column('equipment_read', sa.Boolean(), nullable=False),
    sa.Column('equipment_modify', sa.Boolean(), nullable=False),
    sa.Column('equipment_create', sa.Boolean(), nullable=False),
    sa.Column('equipment_delete', sa.Boolean(), nullable=False),
    sa.Column('object_read', sa.Boolean(), nullable=False),
    sa.Column('object_modify', sa.Boolean(), nullable=False),
    sa.Column('object_create', sa.Boolean(), nullable=False),
    sa.Column('object_delete', sa.Boolean(), nullable=False),
    sa.Column('object_equipment_read', sa.Boolean(), nullable=False),
    sa.Column('object_equipment_modify', sa.Boolean(), nullable=False),
    sa.Column('object_equipment_create', sa.Boolean(), nullable=False),
    sa.Column('object_equipment_delete', sa.Boolean(), nullable=False),
    sa.Column('operation_read', sa.Boolean(), nullable=False),
    sa.Column('operation_modify', sa.Boolean(), nullable=False),
    sa.Column('operation_create', sa.Boolean(), nullable=False),
    sa.Column('operation_delete', sa.Boolean(), nullable=False),
    sa.Column('spec_job_title_read', sa.Boolean(), nullable=False),
    sa.Column('spec_job_title_modify', sa.Boolean(), nullable=False),
    sa.Column('spec_job_title_create', sa.Boolean(), nullable=False),
    sa.Column('spec_job_title_delete', sa.Boolean(), nullable=False),
    sa.Column('spec_order_read', sa.Boolean(), nullable=False),
    sa.Column('spec_order_create', sa.Boolean(), nullable=False),
    sa.Column('spec_order_modify', sa.Boolean(), nullable=False),
    sa.Column('spec_order_delete', sa.Boolean(), nullable=False),
    sa.Column('spec_system_read', sa.Boolean(), nullable=False),
    sa.Column('spec_system_create', sa.Boolean(), nullable=False),
    sa.Column('spec_system_modify', sa.Boolean(), nullable=False),
    sa.Column('spec_system_delete', sa.Boolean(), nullable=False),
    sa.Column('order_read', sa.Boolean(), nullable=False),
    sa.Column('order_create', sa.Boolean(), nullable=False),
    sa.Column('order_modify', sa.Boolean(), nullable=False),
    sa.Column('order_delete', sa.Boolean(), nullable=False),
    sa.Column('report_read', sa.Boolean(), nullable=False),
    sa.Column('report_create', sa.Boolean(), nullable=False),
    sa.Column('report_modify', sa.Boolean(), nullable=False),
    sa.Column('report_delete', sa.Boolean(), nullable=False),
    sa.Column('issue_read', sa.Boolean(), nullable=False),
    sa.Column('issue_create', sa.Boolean(), nullable=False),
    sa.Column('issue_modify', sa.Boolean(), nullable=False),
    sa.Column('issue_delete', sa.Boolean(), nullable=False),
    sa.Column('spec_status_read', sa.Boolean(), nullable=False),
    sa.Column('spec_status_create', sa.Boolean(), nullable=False),
    sa.Column('spec_status_modify', sa.Boolean(), nullable=False),
    sa.Column('spec_status_delete', sa.Boolean(), nullable=False),
    sa.Column('spec_priority_read', sa.Boolean(), nullable=False),
    sa.Column('spec_priority_create', sa.Boolean(), nullable=False),
    sa.Column('spec_priority_modify', sa.Boolean(), nullable=False),
    sa.Column('spec_priority_delete', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('spec_arials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('spec_builds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('spec_contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('spec_equipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('spec_job_titles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('spec_localitys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('short_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('spec_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('short_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('spec_prioritys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('spec_regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('spec_rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('spec_statuss',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('spec_streets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('short_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('spec_systems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False, comment='Наименование типа системы'),
    sa.Column('short_name', sa.String(), nullable=True, comment='Сокращённое наименование'),
    sa.Column('is_fire_protection', sa.Boolean(), nullable=False, comment='Принадлежность к средствам и системам противопожарной защиты'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('arials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('spec_arial_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['spec_arial_id'], ['spec_arials.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('equipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False, comment='Наименование оборудования'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Активно (true) / списано (false)'),
    sa.Column('spec_equipment_id', sa.Integer(), nullable=False, comment='ID типа оборудования'),
    sa.Column('spec_system_id', sa.Integer(), nullable=True, comment='ID типа обслуживаемой системы по умолчанию (опционально)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['spec_equipment_id'], ['spec_equipments.id'], ),
    sa.ForeignKeyConstraint(['spec_system_id'], ['spec_systems.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('localitys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('spec_locality_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['spec_locality_id'], ['spec_localitys.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('operations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('short_name', sa.String(), nullable=True),
    sa.Column('period_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['period_id'], ['periods.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('spec_region_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['spec_region_id'], ['spec_regions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('symbol')
    )
    op.create_table('streets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('spec_street_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['spec_street_id'], ['spec_streets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('hash', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('telegram_id', sa.String(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('operations_spec_equipments',
    sa.Column('operation_id', sa.Integer(), nullable=False),
    sa.Column('spec_equipment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['spec_equipment_id'], ['spec_equipments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('operation_id', 'spec_equipment_id')
    )
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('short_name', sa.String(), nullable=False),
    sa.Column('inn', sa.String(), nullable=False),
    sa.Column('kpp', sa.String(), nullable=False),
    sa.Column('director_first_name', sa.String(), nullable=False),
    sa.Column('drector_last_name', sa.String(), nullable=False),
    sa.Column('drector_surname', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('telephone', sa.String(), nullable=True),
    sa.Column('site', sa.String(), nullable=True),
    sa.Column('corr_check', sa.String(), nullable=False),
    sa.Column('acc_check', sa.String(), nullable=False),
    sa.Column('pers_check', sa.String(), nullable=False),
    sa.Column('build_number', sa.String(), nullable=True),
    sa.Column('room_number', sa.String(), nullable=True),
    sa.Column('customer', sa.Boolean(), nullable=False),
    sa.Column('executor', sa.Boolean(), nullable=False),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.Column('bank_id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('arial_id', sa.Integer(), nullable=False),
    sa.Column('locality_id', sa.Integer(), nullable=False),
    sa.Column('street_id', sa.Integer(), nullable=False),
    sa.Column('spec_build_id', sa.Integer(), nullable=False),
    sa.Column('spec_room_id', sa.Integer(), nullable=True),
    sa.Column('spec_job_title_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['arial_id'], ['arials.id'], ),
    sa.ForeignKeyConstraint(['bank_id'], ['banks.id'], ),
    sa.ForeignKeyConstraint(['locality_id'], ['localitys.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.ForeignKeyConstraint(['spec_build_id'], ['spec_builds.id'], ),
    sa.ForeignKeyConstraint(['spec_job_title_id'], ['spec_job_titles.id'], ),
    sa.ForeignKeyConstraint(['spec_room_id'], ['spec_rooms.id'], ),
    sa.ForeignKeyConstraint(['street_id'], ['streets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inn'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('short_name')
    )
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(), nullable=False),
    sa.Column('date_of_consclusion', sa.Date(), nullable=False),
    sa.Column('date_of_completion', sa.Date(), nullable=False),
    sa.Column('summ', sa.Float(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('short_subject', sa.String(), nullable=False),
    sa.Column('type_contract', sa.String(), nullable=False),
    sa.Column('spec_contract_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('executor_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['executor_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['spec_contract_id'], ['spec_contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('objects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('build_number', sa.String(), nullable=True),
    sa.Column('room_number', sa.String(), nullable=True),
    sa.Column('responsible_face', sa.String(), nullable=False),
    sa.Column('responsible_faces_contact', sa.String(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('arial_id', sa.Integer(), nullable=False),
    sa.Column('locality_id', sa.Integer(), nullable=False),
    sa.Column('street_id', sa.Integer(), nullable=False),
    sa.Column('spec_build_id', sa.Integer(), nullable=False),
    sa.Column('spec_room_id', sa.Integer(), nullable=True),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('number_in_contract', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['arial_id'], ['arials.id'], ),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['locality_id'], ['localitys.id'], ),
    sa.ForeignKeyConstraint(['period_id'], ['periods.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.ForeignKeyConstraint(['spec_build_id'], ['spec_builds.id'], ),
    sa.ForeignKeyConstraint(['spec_room_id'], ['spec_rooms.id'], ),
    sa.ForeignKeyConstraint(['street_id'], ['streets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_id', 'number_in_contract', name='uq_object_contract_number_in_contract')
    )
    op.create_table('sub_contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(), nullable=False),
    sa.Column('date_of_consclusion', sa.Date(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('objects_equipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False, comment='Количество единиц оборудования на объекте'),
    sa.Column('inventory_number', sa.String(), nullable=True, comment='Инвентарный номер экземпляра на объекте'),
    sa.Column('serial_number', sa.String(), nullable=True, comment='Серийный (заводской) номер экземпляра на объекте'),
    sa.Column('installation_date', sa.Date(), nullable=True, comment='Дата установки/ввода в эксплуатацию'),
    sa.Column('object_id', sa.Integer(), nullable=False, comment='ID объекта'),
    sa.Column('equipment_id', sa.Integer(), nullable=False, comment='ID оборудования'),
    sa.Column('spec_system_id', sa.Integer(), nullable=True, comment='ID типа обслуживаемой системы (опционально)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipments.id'], ),
    sa.ForeignKeyConstraint(['object_id'], ['objects.id'], ),
    sa.ForeignKeyConstraint(['spec_system_id'], ['spec_systems.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_id', 'equipment_id', name='uq_object_equipment')
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['object_id'], ['objects.id'], ),
    sa.ForeignKeyConstraint(['period_id'], ['periods.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['spec_statuss.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=False, comment='Номер неисправности'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='Краткое описание'),
    sa.Column('description', sa.Text(), nullable=True, comment='Подробное описание'),
    sa.Column('status_id', sa.Integer(), nullable=False, comment='ID статуса из справочника spec_statuss'),
    sa.Column('priority_id', sa.Integer(), nullable=False, comment='ID приоритета из справочника spec_prioritys'),
    sa.Column('detected_date', sa.Date(), nullable=False, comment='Дата обнаружения'),
    sa.Column('resolved_date', sa.Date(), nullable=True, comment='Дата устранения'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Дата создания записи'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Дата обновления'),
    sa.Column('is_resolved', sa.Boolean(), nullable=False, comment='Признак устранения'),
    sa.Column('is_critical', sa.Boolean(), nullable=False, comment='Критическая неисправность'),
    sa.Column('object_equipment_id', sa.Integer(), nullable=False, comment='ID связи объекта с оборудованием'),
    sa.Column('reported_by_id', sa.Integer(), nullable=False, comment='ID пользователя, сообщившего о неисправности'),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True, comment='ID ответственного пользователя'),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['object_equipment_id'], ['objects_equipments.id'], ),
    sa.ForeignKeyConstraint(['priority_id'], ['spec_prioritys.id'], ),
    sa.ForeignKeyConstraint(['reported_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['spec_statuss.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(), nullable=False),
    sa.Column('spec_order_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['object_id'], ['objects.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['spec_order_id'], ['spec_orders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number'),
    sa.UniqueConstraint('report_id')
    )
    op.create_table('report_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('pdf_path', sa.String(length=512), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('pages', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_attachments_report_id'), 'report_attachments', ['report_id'], unique=False)
    op.create_table('issue_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('pdf_path', sa.String(length=512), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('pages', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issue_attachments_issue_id'), 'issue_attachments', ['issue_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_issue_attachments_issue_id'), table_name='issue_attachments')
    op.drop_table('issue_attachments')
    op.drop_index(op.f('ix_report_attachments_report_id'), table_name='report_attachments')
    op.drop_table('report_attachments')
    op.drop_table('orders')
    op.drop_table('issues')
    op.drop_table('reports')
    op.drop_table('objects_equipments')
    op.drop_table('sub_contracts')
    op.drop_table('objects')
    op.drop_table('contracts')
    op.drop_table('organizations')
    op.drop_table('operations_spec_equipments')
    op.drop_table('users')
    op.drop_table('streets')
    op.drop_table('regions')
    op.drop_table('operations')
    op.drop_table('localitys')
    op.drop_table('equipments')
    op.drop_table('arials')
    op.drop_table('spec_systems')
    op.drop_table('spec_streets')
    op.drop_table('spec_statuss')
    op.drop_table('spec_rooms')
    op.drop_table('spec_regions')
    op.drop_table('spec_prioritys')
    op.drop_table('spec_orders')
    op.drop_table('spec_localitys')
    op.drop_table('spec_job_titles')
    op.drop_table('spec_equipments')
    op.drop_table('spec_contracts')
    op.drop_table('spec_builds')
    op.drop_table('spec_arials')
    op.drop_table('roles')
    op.drop_table('periods')
    op.drop_table('banks')
    # ### end Alembic commands ###
