"""initial for new project

Revision ID: 8e670b71f529
Revises: 
Create Date: 2025-04-22 23:14:50.887202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8e670b71f529'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_read', sa.Boolean(), nullable=False),
    sa.Column('user_modify', sa.Boolean(), nullable=False),
    sa.Column('user_create', sa.Boolean(), nullable=False),
    sa.Column('user_delete', sa.Boolean(), nullable=False),
    sa.Column('role_read', sa.Boolean(), nullable=False),
    sa.Column('role_modify', sa.Boolean(), nullable=False),
    sa.Column('role_create', sa.Boolean(), nullable=False),
    sa.Column('role_delete', sa.Boolean(), nullable=False),
    sa.Column('spec_region_read', sa.Boolean(), nullable=False),
    sa.Column('spec_region_modify', sa.Boolean(), nullable=False),
    sa.Column('spec_region_create', sa.Boolean(), nullable=False),
    sa.Column('spec_region_delete', sa.Boolean(), nullable=False),
    sa.Column('region_read', sa.Boolean(), nullable=False),
    sa.Column('region_modify', sa.Boolean(), nullable=False),
    sa.Column('region_create', sa.Boolean(), nullable=False),
    sa.Column('region_delete', sa.Boolean(), nullable=False),
    sa.Column('spec_arial_read', sa.Boolean(), nullable=False),
    sa.Column('spec_arial_modify', sa.Boolean(), nullable=False),
    sa.Column('spec_arial_create', sa.Boolean(), nullable=False),
    sa.Column('spec_arial_delete', sa.Boolean(), nullable=False),
    sa.Column('arial_read', sa.Boolean(), nullable=False),
    sa.Column('arial_modify', sa.Boolean(), nullable=False),
    sa.Column('arial_create', sa.Boolean(), nullable=False),
    sa.Column('arial_delete', sa.Boolean(), nullable=False),
    sa.Column('spec_locality_read', sa.Boolean(), nullable=False),
    sa.Column('spec_locality_modify', sa.Boolean(), nullable=False),
    sa.Column('spec_locality_create', sa.Boolean(), nullable=False),
    sa.Column('spec_locality_delete', sa.Boolean(), nullable=False),
    sa.Column('locality_read', sa.Boolean(), nullable=False),
    sa.Column('locality_modify', sa.Boolean(), nullable=False),
    sa.Column('locality_create', sa.Boolean(), nullable=False),
    sa.Column('locality_delete', sa.Boolean(), nullable=False),
    sa.Column('spec_street_read', sa.Boolean(), nullable=False),
    sa.Column('spec_street_modify', sa.Boolean(), nullable=False),
    sa.Column('spec_street_create', sa.Boolean(), nullable=False),
    sa.Column('spec_street_delete', sa.Boolean(), nullable=False),
    sa.Column('street_read', sa.Boolean(), nullable=False),
    sa.Column('street_modify', sa.Boolean(), nullable=False),
    sa.Column('street_create', sa.Boolean(), nullable=False),
    sa.Column('street_delete', sa.Boolean(), nullable=False),
    sa.Column('spec_build_read', sa.Boolean(), nullable=False),
    sa.Column('spec_build_modify', sa.Boolean(), nullable=False),
    sa.Column('spec_build_create', sa.Boolean(), nullable=False),
    sa.Column('spec_build_delete', sa.Boolean(), nullable=False),
    sa.Column('spec_room_read', sa.Boolean(), nullable=False),
    sa.Column('spec_room_modify', sa.Boolean(), nullable=False),
    sa.Column('spec_room_create', sa.Boolean(), nullable=False),
    sa.Column('spec_room_delete', sa.Boolean(), nullable=False),
    sa.Column('bank_read', sa.Boolean(), nullable=False),
    sa.Column('bank_modify', sa.Boolean(), nullable=False),
    sa.Column('bank_create', sa.Boolean(), nullable=False),
    sa.Column('bank_delete', sa.Boolean(), nullable=False),
    sa.Column('organization_read', sa.Boolean(), nullable=False),
    sa.Column('organization_modify', sa.Boolean(), nullable=False),
    sa.Column('organization_create', sa.Boolean(), nullable=False),
    sa.Column('organization_delete', sa.Boolean(), nullable=False),
    sa.Column('spec_contract_read', sa.Boolean(), nullable=False),
    sa.Column('spec_contract_modify', sa.Boolean(), nullable=False),
    sa.Column('spec_contract_create', sa.Boolean(), nullable=False),
    sa.Column('spec_contract_delete', sa.Boolean(), nullable=False),
    sa.Column('contract_read', sa.Boolean(), nullable=False),
    sa.Column('contract_modify', sa.Boolean(), nullable=False),
    sa.Column('contract_create', sa.Boolean(), nullable=False),
    sa.Column('contract_delete', sa.Boolean(), nullable=False),
    sa.Column('period_read', sa.Boolean(), nullable=False),
    sa.Column('period_modify', sa.Boolean(), nullable=False),
    sa.Column('period_create', sa.Boolean(), nullable=False),
    sa.Column('period_delete', sa.Boolean(), nullable=False),
    sa.Column('spec_equipment_read', sa.Boolean(), nullable=False),
    sa.Column('spec_equipment_modify', sa.Boolean(), nullable=False),
    sa.Column('spec_equipment_create', sa.Boolean(), nullable=False),
    sa.Column('spec_equipment_delete', sa.Boolean(), nullable=False),
    sa.Column('equipment_read', sa.Boolean(), nullable=False),
    sa.Column('equipment_modify', sa.Boolean(), nullable=False),
    sa.Column('equipment_create', sa.Boolean(), nullable=False),
    sa.Column('equipment_delete', sa.Boolean(), nullable=False),
    sa.Column('object_read', sa.Boolean(), nullable=False),
    sa.Column('object_modify', sa.Boolean(), nullable=False),
    sa.Column('object_create', sa.Boolean(), nullable=False),
    sa.Column('object_delete', sa.Boolean(), nullable=False),
    sa.Column('object_equipment_read', sa.Boolean(), nullable=False),
    sa.Column('object_equipment_modify', sa.Boolean(), nullable=False),
    sa.Column('object_equipment_create', sa.Boolean(), nullable=False),
    sa.Column('object_equipment_delete', sa.Boolean(), nullable=False),
    sa.Column('operation_read', sa.Boolean(), nullable=False),
    sa.Column('operation_modify', sa.Boolean(), nullable=False),
    sa.Column('operation_create', sa.Boolean(), nullable=False),
    sa.Column('operation_delete', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('hash', sa.String(), nullable=False),
    sa.Column('telegram_id', sa.String(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('operations')
    op.drop_table('localitys')
    op.drop_table('regions')
    op.drop_table('spec_contracts')
    op.drop_table('spec_localitys')
    op.drop_table('periods')
    op.drop_table('objects')
    op.drop_table('spec_regions')
    op.drop_table('objects_equipments')
    op.drop_table('organizations')
    op.drop_table('arials')
    op.drop_table('streets')
    op.drop_table('equipments')
    op.drop_table('spec_builds')
    op.drop_table('spec_streets')
    op.drop_table('spec_rooms')
    op.drop_table('contracts')
    op.drop_table('spec_job_titles')
    op.drop_table('sub_contracts')
    op.drop_table('banks')
    op.drop_table('spec_arials')
    op.drop_table('spec_equipments')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spec_equipments',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('spec_equipments_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='spec_equipments_pkey'),
    sa.UniqueConstraint('name', name='spec_equipments_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('spec_arials',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('spec_arials_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='spec_arials_pkey'),
    sa.UniqueConstraint('name', name='spec_arials_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('banks',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('banks_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('bik', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('inn', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='banks_pkey'),
    sa.UniqueConstraint('inn', name='banks_inn_key'),
    sa.UniqueConstraint('name', name='banks_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('sub_contracts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('date_of_consclusion', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('subject', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('contract_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], name='sub_contracts_contract_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='sub_contracts_pkey')
    )
    op.create_table('spec_job_titles',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('spec_job_titles_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='spec_job_titles_pkey'),
    sa.UniqueConstraint('name', name='spec_job_titles_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('contracts',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('contracts_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('date_of_consclusion', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('date_of_completion', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('summ', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('subject', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('short_subject', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('type_contract', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('exeсutor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('spec_contract_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['organizations.id'], name='contracts_customer_id_fkey'),
    sa.ForeignKeyConstraint(['exeсutor_id'], ['organizations.id'], name='contracts_exeсutor_id_fkey'),
    sa.ForeignKeyConstraint(['spec_contract_id'], ['spec_contracts.id'], name='contracts_spec_contract_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='contracts_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('spec_rooms',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('spec_rooms_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='spec_rooms_pkey'),
    sa.UniqueConstraint('name', name='spec_rooms_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('spec_streets',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('spec_streets_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='spec_streets_pkey'),
    sa.UniqueConstraint('name', name='spec_streets_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('spec_builds',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('spec_builds_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='spec_builds_pkey'),
    sa.UniqueConstraint('name', name='spec_builds_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('equipments',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('equipments_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('spec_equipment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['spec_equipment_id'], ['spec_equipments.id'], name='equipments_spec_equipment_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='equipments_pkey'),
    sa.UniqueConstraint('name', name='equipments_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('streets',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('streets_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('spec_street_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['spec_street_id'], ['spec_streets.id'], name='streets_spec_street_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='streets_pkey'),
    sa.UniqueConstraint('name', name='streets_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('arials',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('arials_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('spec_arial_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['spec_arial_id'], ['spec_arials.id'], name='arials_spec_arial_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='arials_pkey'),
    sa.UniqueConstraint('name', name='arials_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('organizations',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('organizations_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('short_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('inn', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('kpp', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('director_first_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('drector_last_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('drector_surname', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('telephone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('site', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('corr_check', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('acc_check', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('build_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('room_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('customer', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('executor', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('bank_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('region_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('arial_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('locality_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('street_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('spec_build_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('spec_room_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('spec_job_title_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['arial_id'], ['arials.id'], name='organizations_arial_id_fkey'),
    sa.ForeignKeyConstraint(['bank_id'], ['banks.id'], name='organizations_bank_id_fkey'),
    sa.ForeignKeyConstraint(['locality_id'], ['localitys.id'], name='organizations_locality_id_fkey'),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name='organizations_region_id_fkey'),
    sa.ForeignKeyConstraint(['spec_build_id'], ['spec_builds.id'], name='organizations_spec_build_id_fkey'),
    sa.ForeignKeyConstraint(['spec_job_title_id'], ['spec_job_titles.id'], name='organizations_spec_job_title_id_fkey'),
    sa.ForeignKeyConstraint(['spec_room_id'], ['spec_rooms.id'], name='organizations_spec_room_id_fkey'),
    sa.ForeignKeyConstraint(['street_id'], ['streets.id'], name='organizations_street_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='organizations_pkey'),
    sa.UniqueConstraint('inn', name='organizations_inn_key'),
    sa.UniqueConstraint('name', name='organizations_name_key'),
    sa.UniqueConstraint('short_name', name='organizations_short_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('objects_equipments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('object_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('equipment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipments.id'], name='objects_equipments_equipment_id_fkey'),
    sa.ForeignKeyConstraint(['object_id'], ['objects.id'], name='objects_equipments_object_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='objects_equipments_pkey')
    )
    op.create_table('spec_regions',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('spec_regions_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='spec_regions_pkey'),
    sa.UniqueConstraint('name', name='spec_regions_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('objects',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('build_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('room_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('responsible_face', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('responsible_faces_contact', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('region_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('arial_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('locality_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('street_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('spec_build_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('spec_room_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('period_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('contract_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['arial_id'], ['arials.id'], name='objects_arial_id_fkey'),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], name='objects_contract_id_fkey'),
    sa.ForeignKeyConstraint(['locality_id'], ['localitys.id'], name='objects_locality_id_fkey'),
    sa.ForeignKeyConstraint(['period_id'], ['periods.id'], name='objects_period_id_fkey'),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name='objects_region_id_fkey'),
    sa.ForeignKeyConstraint(['spec_build_id'], ['spec_builds.id'], name='objects_spec_build_id_fkey'),
    sa.ForeignKeyConstraint(['spec_room_id'], ['spec_rooms.id'], name='objects_spec_room_id_fkey'),
    sa.ForeignKeyConstraint(['street_id'], ['streets.id'], name='objects_street_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='objects_pkey')
    )
    op.create_table('periods',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('periods_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('period', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='periods_pkey'),
    sa.UniqueConstraint('name', name='periods_name_key'),
    sa.UniqueConstraint('period', name='periods_period_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('spec_localitys',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('spec_localitys_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='spec_localitys_pkey'),
    sa.UniqueConstraint('name', name='spec_localitys_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('spec_contracts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='spec_contracts_pkey'),
    sa.UniqueConstraint('name', name='spec_contracts_name_key')
    )
    op.create_table('regions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('spec_region_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['spec_region_id'], ['spec_regions.id'], name='regions_spec_region_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='regions_pkey'),
    sa.UniqueConstraint('name', name='regions_name_key'),
    sa.UniqueConstraint('symbol', name='regions_symbol_key')
    )
    op.create_table('localitys',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('spec_locality_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['spec_locality_id'], ['spec_localitys.id'], name='localitys_spec_locality_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='localitys_pkey'),
    sa.UniqueConstraint('name', name='localitys_name_key')
    )
    op.create_table('operations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('scope', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('period_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['period_id'], ['periods.id'], name='operations_period_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='operations_pkey'),
    sa.UniqueConstraint('name', name='operations_name_key')
    )
    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###
