"""added a few models

Revision ID: c2d40b08d5a3
Revises: 
Create Date: 2025-06-04 22:01:08.346545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c2d40b08d5a3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_read', sa.Boolean(), nullable=False),
    sa.Column('user_modify', sa.Boolean(), nullable=False),
    sa.Column('user_create', sa.Boolean(), nullable=False),
    sa.Column('user_delete', sa.Boolean(), nullable=False),
    sa.Column('role_read', sa.Boolean(), nullable=False),
    sa.Column('role_modify', sa.Boolean(), nullable=False),
    sa.Column('role_create', sa.Boolean(), nullable=False),
    sa.Column('role_delete', sa.Boolean(), nullable=False),
    sa.Column('spec_region_read', sa.Boolean(), nullable=False),
    sa.Column('spec_region_modify', sa.Boolean(), nullable=False),
    sa.Column('spec_region_create', sa.Boolean(), nullable=False),
    sa.Column('spec_region_delete', sa.Boolean(), nullable=False),
    sa.Column('region_read', sa.Boolean(), nullable=False),
    sa.Column('region_modify', sa.Boolean(), nullable=False),
    sa.Column('region_create', sa.Boolean(), nullable=False),
    sa.Column('region_delete', sa.Boolean(), nullable=False),
    sa.Column('spec_arial_read', sa.Boolean(), nullable=False),
    sa.Column('spec_arial_modify', sa.Boolean(), nullable=False),
    sa.Column('spec_arial_create', sa.Boolean(), nullable=False),
    sa.Column('spec_arial_delete', sa.Boolean(), nullable=False),
    sa.Column('arial_read', sa.Boolean(), nullable=False),
    sa.Column('arial_modify', sa.Boolean(), nullable=False),
    sa.Column('arial_create', sa.Boolean(), nullable=False),
    sa.Column('arial_delete', sa.Boolean(), nullable=False),
    sa.Column('spec_locality_read', sa.Boolean(), nullable=False),
    sa.Column('spec_locality_modify', sa.Boolean(), nullable=False),
    sa.Column('spec_locality_create', sa.Boolean(), nullable=False),
    sa.Column('spec_locality_delete', sa.Boolean(), nullable=False),
    sa.Column('locality_read', sa.Boolean(), nullable=False),
    sa.Column('locality_modify', sa.Boolean(), nullable=False),
    sa.Column('locality_create', sa.Boolean(), nullable=False),
    sa.Column('locality_delete', sa.Boolean(), nullable=False),
    sa.Column('spec_street_read', sa.Boolean(), nullable=False),
    sa.Column('spec_street_modify', sa.Boolean(), nullable=False),
    sa.Column('spec_street_create', sa.Boolean(), nullable=False),
    sa.Column('spec_street_delete', sa.Boolean(), nullable=False),
    sa.Column('street_read', sa.Boolean(), nullable=False),
    sa.Column('street_modify', sa.Boolean(), nullable=False),
    sa.Column('street_create', sa.Boolean(), nullable=False),
    sa.Column('street_delete', sa.Boolean(), nullable=False),
    sa.Column('spec_build_read', sa.Boolean(), nullable=False),
    sa.Column('spec_build_modify', sa.Boolean(), nullable=False),
    sa.Column('spec_build_create', sa.Boolean(), nullable=False),
    sa.Column('spec_build_delete', sa.Boolean(), nullable=False),
    sa.Column('spec_room_read', sa.Boolean(), nullable=False),
    sa.Column('spec_room_modify', sa.Boolean(), nullable=False),
    sa.Column('spec_room_create', sa.Boolean(), nullable=False),
    sa.Column('spec_room_delete', sa.Boolean(), nullable=False),
    sa.Column('bank_read', sa.Boolean(), nullable=False),
    sa.Column('bank_modify', sa.Boolean(), nullable=False),
    sa.Column('bank_create', sa.Boolean(), nullable=False),
    sa.Column('bank_delete', sa.Boolean(), nullable=False),
    sa.Column('organization_read', sa.Boolean(), nullable=False),
    sa.Column('organization_modify', sa.Boolean(), nullable=False),
    sa.Column('organization_create', sa.Boolean(), nullable=False),
    sa.Column('organization_delete', sa.Boolean(), nullable=False),
    sa.Column('spec_contract_read', sa.Boolean(), nullable=False),
    sa.Column('spec_contract_modify', sa.Boolean(), nullable=False),
    sa.Column('spec_contract_create', sa.Boolean(), nullable=False),
    sa.Column('spec_contract_delete', sa.Boolean(), nullable=False),
    sa.Column('contract_read', sa.Boolean(), nullable=False),
    sa.Column('contract_modify', sa.Boolean(), nullable=False),
    sa.Column('contract_create', sa.Boolean(), nullable=False),
    sa.Column('contract_delete', sa.Boolean(), nullable=False),
    sa.Column('period_read', sa.Boolean(), nullable=False),
    sa.Column('period_modify', sa.Boolean(), nullable=False),
    sa.Column('period_create', sa.Boolean(), nullable=False),
    sa.Column('period_delete', sa.Boolean(), nullable=False),
    sa.Column('spec_equipment_read', sa.Boolean(), nullable=False),
    sa.Column('spec_equipment_modify', sa.Boolean(), nullable=False),
    sa.Column('spec_equipment_create', sa.Boolean(), nullable=False),
    sa.Column('spec_equipment_delete', sa.Boolean(), nullable=False),
    sa.Column('equipment_read', sa.Boolean(), nullable=False),
    sa.Column('equipment_modify', sa.Boolean(), nullable=False),
    sa.Column('equipment_create', sa.Boolean(), nullable=False),
    sa.Column('equipment_delete', sa.Boolean(), nullable=False),
    sa.Column('object_read', sa.Boolean(), nullable=False),
    sa.Column('object_modify', sa.Boolean(), nullable=False),
    sa.Column('object_create', sa.Boolean(), nullable=False),
    sa.Column('object_delete', sa.Boolean(), nullable=False),
    sa.Column('object_equipment_read', sa.Boolean(), nullable=False),
    sa.Column('object_equipment_modify', sa.Boolean(), nullable=False),
    sa.Column('object_equipment_create', sa.Boolean(), nullable=False),
    sa.Column('object_equipment_delete', sa.Boolean(), nullable=False),
    sa.Column('operation_read', sa.Boolean(), nullable=False),
    sa.Column('operation_modify', sa.Boolean(), nullable=False),
    sa.Column('operation_create', sa.Boolean(), nullable=False),
    sa.Column('operation_delete', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('hash', sa.String(), nullable=False),
    sa.Column('telegram_id', sa.String(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('operations')
    op.add_column('localitys', sa.Column('spec_locallity_id', sa.Integer(), nullable=True))
    op.drop_constraint('localitys_spec_locality_id_fkey', 'localitys', type_='foreignkey')
    op.create_foreign_key(None, 'localitys', 'spec_localitys', ['spec_locallity_id'], ['id'])
    op.drop_column('localitys', 'spec_locality_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('localitys', sa.Column('spec_locality_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'localitys', type_='foreignkey')
    op.create_foreign_key('localitys_spec_locality_id_fkey', 'localitys', 'spec_localitys', ['spec_locality_id'], ['id'])
    op.drop_column('localitys', 'spec_locallity_id')
    op.create_table('operations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('scope', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('period_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['period_id'], ['periods.id'], name='operations_period_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='operations_pkey'),
    sa.UniqueConstraint('name', name='operations_name_key')
    )
    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###
