from pydantic import BaseModel, ConfigDict

class RoleResponse(BaseModel):
    # id: int
    name: str
    description: str | None = None
    is_admin:bool
    is_superadmin:bool
    user_read:bool
    user_modify:bool
    user_create:bool
    user_delete:bool
    role_read:bool
    role_modify:bool
    role_create:bool
    role_delete:bool
    spec_region_read:bool
    spec_region_modify:bool
    spec_region_create:bool
    spec_region_delete:bool
    region_read:bool
    region_modify:bool
    region_create:bool
    region_delete:bool
    spec_arial_read:bool
    spec_arial_modify:bool
    spec_arial_create:bool
    spec_arial_delete:bool
    arial_read:bool
    arial_modify:bool
    arial_create:bool
    arial_delete:bool
    spec_locality_read:bool
    spec_locality_modify:bool
    spec_locality_create:bool
    spec_locality_delete:bool
    locality_read:bool
    locality_modify:bool
    locality_create:bool
    locality_delete:bool
    spec_street_read:bool
    spec_street_modify:bool
    spec_street_create:bool
    spec_street_delete:bool
    street_read:bool
    street_modify:bool
    street_create:bool
    street_delete:bool
    spec_build_read:bool
    spec_build_modify:bool
    spec_build_create:bool
    spec_build_delete:bool
    spec_room_read:bool
    spec_room_modify:bool
    spec_room_create:bool
    spec_room_delete:bool
    bank_read:bool
    bank_modify:bool
    bank_create:bool
    bank_delete:bool
    organization_read:bool
    organization_modify:bool
    organization_create:bool
    organization_delete:bool
    spec_contract_read:bool
    spec_contract_modify:bool
    spec_contract_create:bool
    spec_contract_delete:bool
    contract_read:bool
    contract_modify:bool
    contract_create:bool
    contract_delete:bool
    period_read:bool
    period_modify:bool
    period_create:bool
    period_delete:bool
    spec_equipment_read:bool
    spec_equipment_modify:bool
    spec_equipment_create:bool
    spec_equipment_delete:bool
    equipment_read:bool
    equipment_modify:bool
    equipment_create:bool
    equipment_delete:bool
    object_read:bool
    object_modify:bool
    object_create:bool
    object_delete:bool
    object_equipment_read:bool
    object_equipment_modify:bool
    object_equipment_create:bool
    object_equipment_delete:bool
    operation_read:bool
    operation_modify:bool
    operation_create:bool
    operation_delete:bool

    model_config = ConfigDict(from_attributes=True)